// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:93808515-e578-4a06-a80b-19186f8f6f13",
    "aws_cognito_region": "ap-southeast-1",
    "oauth": {}
};


export default awsmobile;
